export const dataAbout = [
    {
        id: crypto.randomUUID(),
        img: '/src/assets/Kathe-black.png',
        img2:"/src/assets/Kathe-color.png",
        name: "Katherine Reyes",
        talents: "UX | UI designer",
        behance: "https://www.behance.net/katherinereyes119",
        github: "https://github.com/kathereyes19",
        biography: "Design student in Cali, Colombia, focused on interactive media and digital communication. I seek to create exceptional digital experiences that drive brands. With about 2 years of experience, I specialize in user experience design (UI/UX), leading innovative projects backed by solid research. I believe in engaging and functional solutions.",
        skill1: "Advertising and brand Design",
        skill2: "Interface Design and Prototyping",
        skill3: "Digital Content Creation",
        skill4: "Front-End Development",
        studies1: "Interactive Media Design - ICESI University",
        studies2: "Communication with Digital Focus - ICESI University",
        path:"./Kathe",
    },
    {
        id: crypto.randomUUID(),
        img: '/src/assets/Impa-black.png',
        img2:"/src/assets/Impa-color.png",
        name: "Sebastián González",
        talents: "UX | UI designer ",
        behance: "https://www.behance.net/sebastigonzale106",
        github: "https://github.com/SebasG819",
        biography: "I'm a sixth-semester student studying Interactive Media Design. I specialize in UX (User Experience) because I'm passionate about creating unforgettable and user-friendly experiences. My goal is to design innovative solutions that connect with users on an emotional level. I'm dedicated to continuous learning and pushing the boundaries of creativity in interactive design.",
        skill1: "Content creation",
        skill2: "Ux",
        skill3: "Front-End Development",
        skill4: "Photography ",
        studies1: "Interactive Media Design - Icesi University",
        studies2: "",
        path:"./Impa",
    },
    {
        id: crypto.randomUUID(),
        img: '/src/assets/Cuadros-black.png',
        img2:"/src/assets/Cuadros-color.png",
        name: "Santiago Cuadros",
        talents: "UX | FrontEnd developer",
        behance: "https://www.behance.net/sacuma09",
        github: "https://github.com/sacuadros09",
        biography: "As a student of interactive media design in Cali, Colombia, my main focus is on creating interactive experiences that captivate through applications and games. My passion for subjects like video games, fitness, soccer, and animation is reflected in the projects I undertake. Specializing in UX and FrontEnd development, I am committed to continuous learning and the pursuit of new ways to innovate in the world of interactive design.",
        skill1: "UX",
        skill2: "Animation",
        skill3: "Front-End Development",
        skill4: "",
        studies1: "Interactive Media Design - ICESI University",
        studies2: "",
        path:"./Cuadros",
    },
    {
        id: crypto.randomUUID(),
        img: '/src/assets/Avila-black.png',
        img2:"/src/assets/Avila-color.png",
        name: "Juan David Avila",
        talents: "UI | FrontEnd devoloper",
        behance: "https://www.behance.net/sacuma09",
        github: "https://github.com/sacuadros09",
        biography: "Interactive Media Design student in Cali, Colombia. Focused on interactive media. With about 1 year of experience, I specialize in user interface design (UI), leading innovative projects backed by solid research. I believe in engaging and functional solutions.",
        skill1: "Advertising and brand Design",
        skill2: "Interface Design and Prototyping",
        skill3: "Front-End Development",
        skill4: "",
        studies1: "Interactive Media Design - ICESI University",
        studies2: "",
        path:"./JD",
    },

]